# Generated by Django 4.2.4 on 2023-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_document_documentchunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
