# Generated by Django 4.2.4 on 2023-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="phx-datasciencellm_django-app"
            ),
        ),
    ]
