# Generated by Django 4.2.4 on 2023-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="original_file_name",
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
