# Generated by Django 4.2.4 on 2023-08-15 22:14

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_document_file_name_remove_document_file_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="document",
            old_name="upload_finished_at",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_overlap",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="summary_embedding",
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="chat.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                related_name="documents", to="chat.documenttag"
            ),
        ),
    ]
