# Generated by Django 4.2.4 on 2023-08-17 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0009_document_mean_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_model",
                    models.CharField(
                        choices=[
                            ("chat-bison", "PaLM chat"),
                            ("codechat-bison", "PaLM chat (code)"),
                        ],
                        default="chat-bison",
                        max_length=255,
                    ),
                ),
                ("system_prompt", models.TextField(null=True)),
                ("max_output_tokens", models.IntegerField(default=1024)),
                ("temperature", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
