# Generated by Django 4.2.4 on 2023-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="chat_model",
            field=models.CharField(
                choices=[
                    ("chat-bison", "Google PaLM chat-bison"),
                    ("codechat-bison", "Google PaLM chat-bison (code)"),
                ],
                default="chat-bison",
                max_length=255,
            ),
        ),
    ]
