# Generated by Django 4.2.4 on 2023-08-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_usersettings_chat_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="system_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
