# Generated by Django 4.2.4 on 2023-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_usersettings_system_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="chat_model",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("chat-bison", "Google PaLM chat-bison"),
                    ("codechat-bison", "Google PaLM codechat-bison"),
                    ("text-bison", "Google PaLM text-bison"),
                    ("code-bison", "Google PaLM code-bison"),
                ],
                default="chat-bison",
                max_length=255,
            ),
        ),
    ]
