# Generated by Django 4.2.4 on 2023-08-18 17:09

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_remove_usersettings_chat_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentchunk",
            name="text",
        ),
        migrations.AddField(
            model_name="document",
            name="chunk_size",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="user_generated",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="chunk_overlap",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                null=True, upload_to=chat.models.user_directory_path
            ),
        ),
    ]
