# Generated by Django 4.2.4 on 2023-08-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_document_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
